In [1]:
import numpy as np

In [6]:
# filtering

ages = np.array([
  [21, 17, 19, 20, 16, 18, 35],
  [25, 30, 15, 14, 28, 40, 50]
])

np.shape(ages)

(2, 7)

In [7]:
underage_mask = ages[ages < 18]
underage_mask

array([17, 16, 15, 14])

In [9]:
adult_mask = ages[(ages >= 18) & (ages < 40)]
adult_mask

array([21, 19, 20, 18, 35, 25, 30, 28])

In [10]:
senior_mask = ages[ages >= 40]
senior_mask

array([40, 50])

In [12]:
adults = np.where((ages >= 18) & (ages < 40), ages, 0)
adults

array([[21,  0, 19, 20,  0, 18, 35],
       [25, 30,  0,  0, 28,  0,  0]])