In [1]:
import numpy as np

In [ ]:
rng = np.random.default_rng(seed=2)
array = rng.integers(low=1, high=100, size=(4, 2))  # 4x2

array

array([[83, 26],
       [11, 30],
       [41, 81],
       [45, 10]])

In [33]:
np.random.seed(42)
np.random.uniform(0.0, 1.0, size=(2, 3, 1))

array([[[0.37454012],
        [0.95071431],
        [0.73199394]],

       [[0.59865848],
        [0.15601864],
        [0.15599452]]])

In [37]:
rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5, 6])
rng.shuffle(array)
array

array([5, 1, 4, 3, 2, 6])

In [47]:
fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])

fruit = rng.choice(fruits, size=(3, 2))
fruit

array([['cherry', 'cherry'],
       ['apple', 'elderberry'],
       ['apple', 'cherry']], dtype='<U10')