In [1]:
import numpy as np

In [2]:
# scalar arithmetic
a = 10
b = 3

a + b, a - b, a * b, a / b, a // b, a % b, a ** b

(13, 7, 30, 3.3333333333333335, 3, 1, 1000)

In [4]:
array = np.array([1, 2, 3, 4])

array + 1, array - 1, array * 2, array / 2, array ** 5

(array([2, 3, 4, 5]),
 array([0, 1, 2, 3]),
 array([2, 4, 6, 8]),
 array([0.5, 1. , 1.5, 2. ]),
 array([   1,   32,  243, 1024]))

In [5]:
# vectorized operations
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

array1 + array2, array1 - array2, array1 * array2, array1 / array2, array1 ** array2

(array([ 6,  8, 10, 12]),
 array([-4, -4, -4, -4]),
 array([ 5, 12, 21, 32]),
 array([0.2       , 0.33333333, 0.42857143, 0.5       ]),
 array([    1,    64,  2187, 65536]))

In [10]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
array = np.array([1, 2, 3, 4])

np.pi * array ** 2

array([ 3.14159265, 12.56637061, 28.27433388, 50.26548246])