In [1]:
import numpy as np


In [3]:
array = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]
])
array.shape, array.dtype, array.ndim

((4, 4), dtype('int64'), 2)

In [6]:
# array[start:end:step]

array[0], array[-1]

(array([1, 2, 3, 4]), array([13, 14, 15, 16]))

In [ ]:
# row slicing
array[0:3], array[:2], array[2:], array[::2]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]))

In [17]:
# column slicing
array[:, 0], array[:, 1:3], array[:, ::2]

(array([ 1,  5,  9, 13]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]]))

In [22]:
# row and column slicing

array[0:2, 0:2], array[0:2, 2:], array[2:4, 0:2], array[2:4, 2:]

(array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]]),
 array([[ 9, 10],
        [13, 14]]),
 array([[11, 12],
        [15, 16]]))